name: LichPrison
version: 1.0
main: main.me.sirlich.Prison.Prison
commands:
   cleardata:
      description: Screw off
      usage: playerdata clear
   state:
      description: Screw off
      usage: Switch state
   zone:
      description: Zone handler
      usage: zone <help, create, inside, delete, list>
   it:
      description: nothing
      usage: what