name: LichPrison
version: 1.0
main: main.me.sirlich.Prison.Prison
commands:
   cleardata:
      description: Screw off
      usage: playerdata clear
   setstate:
      description: Screw off
      usage: Switch state
   zone:
      description: Screw off
      usage: ggg