package main.me.sirlich.Prison.items;

public enum RpgItemType
{
    RAT_BONE,
    RAT_MEAT,
    GOLD_RING,
    STARTER_SWORD,

    //Keys!
    WHITE_GLASS_KEY,
    ORANGE_GLASS_KEY,
    MAGENTA_GLASS_KEY,
    LIGHT_BLUE_GLASS_KEY,
    YELLOW_GLASS_KEY,
    LIME_GLASS_KEY,
    PINK_GLASS_KEY,
    GRAY_GLASS_KEY,
    LIGHT_GRAY_GLASS_KEY,
    CYAN_GLASS_KEY,
    PURPLE_GLASS_KEY,
    BLUE_GLASS_KEY,
    BROWN_GLASS_KEY,
    GREEN_GLASS_KEY,
    RED_GLASS_KEY,
    BLACK_GLASS_KEY,

    WHITE_CONCRETE_KEY,
    ORANGE_CONCRETE_KEY,
    MAGENTA_CONCRETE_KEY,
    LIGHT_BLUE_CONCRETE_KEY,
    YELLOW_CONCRETE_KEY,
    LIME_CONCRETE_KEY,
    PINK_CONCRETE_KEY,
    GRAY_CONCRETE_KEY,
    LIGHT_GRAY_CONCRETE_KEY,
    CYAN_CONCRETE_KEY,
    PURPLE_CONCRETE_KEY,
    BLUE_CONCRETE_KEY,
    BROWN_CONCRETE_KEY,
    GREEN_CONCRETE_KEY,
    RED_CONCRETE_KEY,
    BLACK_CONCRETE_KEY,
}
